/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SpoilerPlugin,
  isSpoiler: () => isSpoiler,
  unwrapSpoiler: () => unwrapSpoiler,
  wrapSpoiler: () => wrapSpoiler
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var SPOILER_HEADER = /^>\s*\[!spoiler\]-?/i;
var SPOILER_HEADER_STRIPPED = /^\[!spoiler\]-?/i;
function isSpoiler(text) {
  const firstLine = text.split("\n").find((line) => line.trim() !== "");
  return firstLine !== void 0 && SPOILER_HEADER.test(firstLine);
}
function wrapSpoiler(text) {
  const body = text.split("\n").map((line) => line === "" ? ">" : "> " + line).join("\n");
  return "> [!spoiler]-\n" + body;
}
function unwrapSpoiler(text) {
  const lines = text.split("\n").map((line) => line.replace(/^> ?/, ""));
  let start = 0;
  for (let i = 0; i < lines.length; i++) {
    if (SPOILER_HEADER_STRIPPED.test(lines[i].trim())) {
      start = i + 1;
      break;
    }
  }
  return lines.slice(start).join("\n");
}
var SpoilerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addRibbonIcon("eye-off", "Toggle spoiler on selection", () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!view) {
        new import_obsidian.Notice("Open a note to toggle a spoiler.");
        return;
      }
      this.toggleSpoiler(view.editor);
    });
    this.addCommand({
      id: "toggle",
      name: "Toggle on selection",
      editorCallback: (editor) => this.toggleSpoiler(editor)
    });
  }
  toggleSpoiler(editor) {
    const selection = editor.getSelection();
    if (selection.length === 0) {
      new import_obsidian.Notice("Select some text to toggle a spoiler.");
      return;
    }
    const replacement = isSpoiler(selection) ? unwrapSpoiler(selection) : wrapSpoiler(selection);
    editor.replaceSelection(replacement);
  }
};

/* nosourcemap */